# Fail2Ban filter MeetrMail management daemon

[INCLUDES]

before = common.conf

[Definition]

_daemon = meetrmail

failregex = MeetrMail Management Daemon: Failed login attempt from ip <HOST> - timestamp .*
ignoreregex =
